
##############################################################################
#
# GitGub CI workflow syntax spec:
#    https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
# CodeCov example:
#    https://github.com/marketplace/actions/coveralls-github-action
#
##############################################################################

name: Build

on:
  # Triggered whenever push to the main branch
  push:
    branches: [ "main" ]

  # Triggered whenever a pull request is created on main
  pull_request:
    branches: [ "main" ]
    types: [opened]

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    # Create a container of the latest Ubuntu, other values could be
    # ubuntu-latest, ubuntu-22.04, etc.
    runs-on: ubuntu-22.04
    
    steps:
      # We want to use GitHub CI checkout version 3 for checking out the branch
      - uses: actions/checkout@v3
      
      # Install some system pacakges
      - name: Install packages
        run: sudo apt install -y lcov ros-humble-ros-base ros-dev-tools 

      # Build for test coverage
      - name: Configure CMake flags and build exectables
        run: |
          colcon build --cmake-args -DCOVERAGE=1 --packages-select cpp_pubsub
          cat log/latest_build/cpp_pubsub/stdout_stderr.log
      
      # Check c++ code (and others) for style and static coding errors
      - name: Check code sytle and error
        run: |
          colcon test --packages-select cpp_pubsub
          cat log/latest_test/cpp_pubsub/stdout_stderr.log

      # Run test suite and compute code coverage
      - name: Run Test Coverage
        run: |
          source install/setup.bash
          timeout 3 ros2 launch cpp_pubsub run_test.launch.py
          ros2 run cpp_pubsub generate_coverage_report.bash
      
      # Upload coverage result to Coverage.io 
      - name: Upload result to Coveralls.io
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{github.workspace}}/install/cpp_pubsub/lib/cpp_pubsub/coverage_cleaned.info
