name: Compile site assets
on: 
  # Triggered whenever push to the main branch
  push:
    branches: [ "test-docker" ]
    
  # Allow manual trigger
  workflow_dispatch:

jobs:
  # compile:
  #   name: Compile assets
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - name: Check out the repo
  #       uses: actions/checkout@v2
  #     - name: Run Docker container
  #       uses: addnab/docker-run-action@v3
  #       with:
  #         image: osrf/ros:humble-desktop
  #         options: -v ${{ github.workspace }}:/app
  #         run: |
  #           apt update
  #           apt -y install ros-humble-gazebo-ros-pkgs 
  #           apt -y install ros-humble-turtlebot3*
  #     - name: Verify 
  #       run: |
  #         pwd
  #         ls -la
  #         uname -a
  #         cat /etc/lsb-release
  compile:
    name: Compile assets
    runs-on: ubuntu-18.04
    container:
      image: osrf/ros:humble-desktop
      volumes:
        - ${{ github.workspace }}:/app
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Install additional packages
        run: |
          apt update
          apt -y install ros-humble-gazebo-ros-pkgs 
          apt -y install ros-humble-turtlebot3*
      - name: Verify 
        run: |
          pwd
          ls -la
          uname -a
          cat /etc/lsb-release
